[target.aarch64-apple-darwin]
rustflags = [
    "-C", "link-arg=-Wl,-rpath,@executable_path/../../../libs/crsdk",
    "-C", "link-arg=-Wl,-rpath,@executable_path/../../../libs/adapters", 
    "-C", "link-arg=-Wl,-rpath,@executable_path/../../../libs/opencv",
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "link-arg=-Wl,-rpath,@executable_path/../../../libs/crsdk",
    "-C", "link-arg=-Wl,-rpath,@executable_path/../../../libs/adapters",
    "-C", "link-arg=-Wl,-rpath,@executable_path/../../../libs/opencv",
]
